from django.contrib import admin
from django.core import mail

from .models import Cp_Currencies, Cp_Wallet, General , Cp_Withdraw, LevelFee, Leverage, MainTradesBuyOrder, MainTradesSellOrder , MainTrades, Perpetual, ProTrades, Notification, Review, SmsVerified, VerifyAcceptRequest, VerifyMelliRequest , BankAccounts , VerifyBankAccountsRequest , Price , Staff, UserInfo , Currencies , Wallet , Verify , BankCards, Transactions, Settings, Subjects, Tickets, Pages, Forgetrequest, VerifyBankRequest, Indexprice, buyoutrequest, buyrequest, selloutrequest, sellrequest
# Register your models here.
admin.site.register(VerifyAcceptRequest)
admin.site.register(selloutrequest)
admin.site.register(LevelFee)
admin.site.register(buyoutrequest)
admin.site.register(buyrequest)
admin.site.register(sellrequest)
admin.site.register(SmsVerified)
admin.site.register(Cp_Wallet)
admin.site.register(Cp_Currencies)
admin.site.register(Review)
admin.site.register(Perpetual)
admin.site.register(General)
admin.site.register(Cp_Withdraw)
admin.site.register(Indexprice)
admin.site.register(Leverage)
admin.site.register(UserInfo)
admin.site.register(Wallet)
admin.site.register(Currencies)
admin.site.register(Verify)
admin.site.register(BankCards)
admin.site.register(Transactions)
admin.site.register(Settings)
admin.site.register(Subjects)
admin.site.register(Tickets)
admin.site.register(Pages)
admin.site.register(Forgetrequest)
admin.site.register(VerifyBankRequest)
admin.site.register(Staff)
admin.site.register(Price)
admin.site.register(VerifyMelliRequest)
admin.site.register(VerifyBankAccountsRequest)
admin.site.register(BankAccounts)
admin.site.register(Notification)
admin.site.register(MainTrades)
admin.site.register(ProTrades)
admin.site.register(MainTradesBuyOrder)
admin.site.register(MainTradesSellOrder)