# Generated by Django 3.2.6 on 2021-10-30 21:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(null=True, upload_to='docs')),
                ('text', models.CharField(max_length=16, null=True)),
                ('img', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cp_Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('chain', models.CharField(max_length=100, null=True)),
                ('can_deposit', models.CharField(max_length=100, null=True)),
                ('can_withdraw', models.CharField(max_length=100, null=True)),
                ('deposit_least_amount', models.CharField(max_length=100, null=True)),
                ('withdraw_least_amount', models.CharField(max_length=100, null=True)),
                ('withdraw_tx_fee', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name=' نام ارز')),
                ('brand', models.CharField(max_length=100, null=True, verbose_name=' نماد ارز')),
                ('pic', models.ImageField(null=True, upload_to='cur')),
            ],
            options={
                'verbose_name': ' ارز ',
                'verbose_name_plural': ' ارز ها',
            },
        ),
        migrations.CreateModel(
            name='Forgetrequest',
            fields=[
                ('email', models.CharField(max_length=200, null=True)),
                ('key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 921029, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('rule', models.CharField(max_length=10000, null=True)),
                ('logo', models.ImageField(null=True, upload_to='general')),
            ],
        ),
        migrations.CreateModel(
            name='Indexprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', jsonfield.fields.JSONField()),
                ('PriceHistory', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LevelFee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('buy', models.FloatField(default=0)),
                ('sell', models.FloatField(default=0)),
                ('perpetual', models.FloatField(default=0)),
                ('margin', models.FloatField(default=0)),
                ('exchange', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Leverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('leverage', models.IntegerField(default=0)),
                ('buymin', models.FloatField(null=True)),
                ('buymax', models.FloatField(null=True)),
                ('sellmin', models.FloatField(null=True)),
                ('sellmax', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=' نام ارز')),
                ('brand', models.CharField(max_length=100, null=True, verbose_name=' نماد ارز')),
                ('bcurrency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buycurrency', to='exchange.currencies')),
                ('scurrency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellcurrency', to='exchange.currencies')),
            ],
        ),
        migrations.CreateModel(
            name='mobilecodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(null=True, upload_to='docs')),
                ('text', models.CharField(max_length=16, null=True)),
                ('img', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(null=True, upload_to='pages')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=10000)),
                ('minitext', models.CharField(default='', max_length=1000)),
                ('position', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(null=True, upload_to='docs')),
                ('text', models.CharField(max_length=16, null=True)),
                ('img', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rial', models.FloatField(default=1)),
                ('btc', models.FloatField(default=0)),
                ('eth', models.FloatField(default=0)),
                ('trx', models.FloatField(default=0)),
                ('usdt', models.FloatField(default=0)),
                ('doge', models.FloatField(default=0)),
                ('usd', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rial', models.FloatField(default=1)),
                ('btc', models.FloatField(default=0)),
                ('eth', models.FloatField(default=0)),
                ('trx', models.FloatField(default=0)),
                ('usdt', models.FloatField(default=0)),
                ('doge', models.FloatField(default=0)),
                ('usd', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=' نام ارز')),
                ('brand', models.CharField(max_length=100, null=True, verbose_name=' نماد ارز')),
                ('bcurrency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='probuycurrency', to='exchange.currencies')),
                ('scurrency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prosellcurrency', to='exchange.currencies')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 906567, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('tel', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=300)),
                ('whatsapp', models.CharField(max_length=300)),
                ('instagram', models.CharField(max_length=300)),
                ('facebook', models.CharField(max_length=300)),
                ('logo', models.ImageField(null=True, upload_to='settings')),
            ],
        ),
        migrations.CreateModel(
            name='SmsVerified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 905849, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 919361, tzinfo=utc))),
                ('act', models.IntegerField(default=0, null=True)),
                ('read', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('aread', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(null=True, upload_to='docs')),
                ('text', models.CharField(max_length=16, null=True)),
                ('img', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('key', models.CharField(blank=True, max_length=1000, null=True)),
                ('accid', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exchange.currencies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' کیف پول ',
                'verbose_name_plural': ' کیف پول ها',
            },
        ),
        migrations.CreateModel(
            name='VerifyMelliRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melliimg', models.ImageField(null=True, upload_to='melli')),
                ('mellic', models.CharField(max_length=16, null=True)),
                ('action', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melli', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyBankRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankc', models.CharField(max_length=16, null=True)),
                ('action', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Banks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyBankAccountsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankc', models.CharField(max_length=16, null=True)),
                ('shebac', models.CharField(max_length=50, null=True)),
                ('action', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BanksAccounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyAcceptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptimg', models.ImageField(upload_to='accept')),
                ('action', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilev', models.BooleanField(default=False, null=True)),
                ('mobilec', models.IntegerField(default=0, null=True)),
                ('emailv', models.BooleanField(default=False, null=True)),
                ('emailc', models.IntegerField(default=0, null=True)),
                ('acceptv', models.BooleanField(default=False, null=True)),
                ('melliv', models.BooleanField(default=False, null=True)),
                ('bankv', models.BooleanField(default=False, null=True)),
                ('accountv', models.BooleanField(default=False, null=True)),
                ('idv', models.BooleanField(default=False, null=True)),
                ('rulev', models.BooleanField(default=False, null=True)),
                ('coinv', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500, null=True)),
                ('post', models.CharField(max_length=10, null=True)),
                ('level', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('smsverify', models.BooleanField(default=False)),
                ('googleverify', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 918262, tzinfo=utc))),
                ('amount', models.FloatField()),
                ('act', models.IntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='exchange.currencies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 919937, tzinfo=utc))),
                ('text', models.CharField(max_length=1000)),
                ('pic', models.ImageField(null=True, upload_to='ticket')),
                ('subid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='exchange.subjects')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harchi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sellrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 908387, tzinfo=utc))),
                ('currency', models.CharField(max_length=20)),
                ('ramount', models.BigIntegerField()),
                ('camount', models.FloatField()),
                ('act', models.IntegerField(default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sells', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='selloutrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 910273, tzinfo=utc))),
                ('currency', models.CharField(max_length=20)),
                ('hash', models.CharField(max_length=200)),
                ('ramount', models.BigIntegerField()),
                ('camount', models.FloatField()),
                ('act', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProTradesSellOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('start', models.FloatField(null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 925632, tzinfo=utc))),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellorders', to='exchange.protrades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protradesellorders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProTradesBuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('start', models.FloatField(null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 925116, tzinfo=utc))),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyorders', to='exchange.protrades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protradebuyorders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerpetualRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 911285, tzinfo=utc))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Perpetualreq', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perpetual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('secretkey', models.CharField(max_length=255)),
                ('apikey', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Perpetual', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=300)),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 922551, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainTradesSellOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('start', models.FloatField(null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 924606, tzinfo=utc))),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellorders', to='exchange.maintrades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintradesellorders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainTradesBuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('start', models.FloatField(null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 924084, tzinfo=utc))),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyorders', to='exchange.maintrades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintradebuyorders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cp_Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 914312, tzinfo=utc))),
                ('chain', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exchange.cp_currencies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cp_Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('currency', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exchange.cp_currencies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='buyrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 907811, tzinfo=utc))),
                ('currency', models.CharField(max_length=20)),
                ('ramount', models.BigIntegerField()),
                ('camount', models.FloatField()),
                ('act', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='buyoutrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 4, 44, 908914, tzinfo=utc))),
                ('currency', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('ramount', models.BigIntegerField()),
                ('camount', models.FloatField()),
                ('act', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=16, null=True)),
                ('shebac', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
