# Generated by Django 3.2.3 on 2021-05-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20210526_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=' نام ارز')),
                ('brand', models.CharField(max_length=100, null=True, verbose_name=' نماد ارز')),
                ('pic', models.ImageField(null=True, upload_to='cur')),
                ('qr', models.ImageField(null=True, upload_to='cur')),
                ('address', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name': ' ارز ',
                'verbose_name_plural': ' ارز ها',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('curid', models.IntegerField(null=True)),
                ('amount', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': ' کیف پول ',
                'verbose_name_plural': ' کیف پول ها',
            },
        ),
    ]
