# Generated by Django 3.2.3 on 2021-05-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20210526_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencies',
            name='qr',
        ),
        migrations.AddField(
            model_name='wallet',
            name='qr',
            field=models.ImageField(null=True, upload_to='cur'),
        ),
    ]
