# Generated by Django 3.2.3 on 2021-05-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20210526_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencies',
            name='address',
        ),
    ]
