# Generated by Django 3.2.3 on 2021-05-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_remove_currencies_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
