# Generated by Django 3.2.3 on 2021-05-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_wallet_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='curid',
            new_name='currency',
        ),
        migrations.AlterField(
            model_name='verify',
            name='bankverify',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='verify',
            name='emailcode',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='verify',
            name='melliverify',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='verify',
            name='mobilecode',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
