# Generated by Django 3.2.6 on 2021-10-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20211030_2104'),
        ('exchange', '0003_auto_20211030_2107'),
        ('exchange', '0008_auto_20211030_2104'),
    ]

    operations = [
    ]
