# Generated by Django 3.2.3 on 2021-06-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20210526_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
