# Generated by Django 3.2.3 on 2021-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_alter_currencies_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
