# Generated by Django 3.2.3 on 2021-06-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_alter_currencies_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='qr',
        ),
    ]
