# Generated by Django 3.2.3 on 2021-06-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_remove_wallet_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='key',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
