# Generated by Django 3.2.3 on 2021-06-04 12:44

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_currencies_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainwalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wall', jsonfield.fields.JSONField()),
            ],
        ),
    ]
