# Generated by Django 3.2.3 on 2021-06-04 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_mainwalls'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainwalls',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainwalls', to='exchange.currencies'),
        ),
    ]
