# Generated by Django 3.2.3 on 2021-06-06 05:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_forgetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetrequest',
            name='key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
