# Generated by Django 3.2.3 on 2021-06-06 05:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0016_alter_forgetrequest_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetrequest',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
