# Generated by Django 3.2.3 on 2021-06-06 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_alter_forgetrequest_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgetrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='forgetrequest',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='forgetrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
