# Generated by Django 3.2.3 on 2021-06-12 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0019_auto_20210607_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 15, 34, 40, 145128)),
        ),
    ]
