# Generated by Django 3.2.3 on 2021-06-12 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0020_alter_forgetrequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifybankrequest',
            name='card',
        ),
        migrations.AlterField(
            model_name='forgetrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 15, 35, 0, 499400)),
        ),
    ]
