# Generated by Django 3.2.3 on 2021-06-23 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0023_auto_20210617_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 12, 35, 47, 557365)),
        ),
    ]
