# Generated by Django 3.2.3 on 2021-06-23 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0024_alter_forgetrequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='key',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='forgetrequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
