# Generated by Django 3.2.3 on 2021-06-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0025_auto_20210623_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.FloatField(default=0)),
                ('eth', models.FloatField(default=0)),
                ('trx', models.FloatField(default=0)),
                ('usdt', models.FloatField(default=0)),
                ('doge', models.FloatField(default=0)),
                ('usd', models.FloatField(default=0)),
            ],
        ),
    ]
