# Generated by Django 3.2.3 on 2021-06-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0026_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='rial',
            field=models.FloatField(default=0),
        ),
    ]
