# Generated by Django 3.2.3 on 2021-07-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0028_auto_20210630_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verify',
            old_name='bankverify',
            new_name='bankv',
        ),
        migrations.RenameField(
            model_name='verify',
            old_name='emailcode',
            new_name='emailc',
        ),
        migrations.RenameField(
            model_name='verify',
            old_name='emailverify',
            new_name='emailv',
        ),
        migrations.RenameField(
            model_name='verify',
            old_name='melliverify',
            new_name='melliv',
        ),
        migrations.RenameField(
            model_name='verify',
            old_name='mobilecode',
            new_name='mobilec',
        ),
        migrations.RenameField(
            model_name='verify',
            old_name='mobileverify',
            new_name='mobilev',
        ),
    ]
