# Generated by Django 3.2.3 on 2021-07-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0031_alter_verifybankrequest_bankc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bankcards',
            name='number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='verifybankaccountsrequest',
            name='bankc',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='verifymellirequest',
            name='mellic',
            field=models.BigIntegerField(null=True),
        ),
    ]
