# Generated by Django 3.2.3 on 2021-07-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0033_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Text',
            new_name='text',
        ),
    ]
