# Generated by Django 3.2.3 on 2021-07-10 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0036_maintrades_protrades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='lastdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
