# Generated by Django 3.2.3 on 2021-07-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0037_auto_20210710_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='lastdate',
        ),
    ]
