# Generated by Django 3.2.3 on 2021-07-12 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0038_remove_subjects_lastdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintrades',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='protrades',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ProTradesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('act', models.BooleanField()),
                ('maintrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange.protrades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protradeorders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainTradesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('act', models.BooleanField()),
                ('maintrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange.maintrades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintradeorders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
