# Generated by Django 3.2.3 on 2021-07-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0040_auto_20210712_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintrades',
            name='bcurrency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buycurrency', to='exchange.currencies'),
        ),
        migrations.AddField(
            model_name='maintrades',
            name='scurrency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellcurrency', to='exchange.currencies'),
        ),
    ]
