# Generated by Django 3.2.3 on 2021-07-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0041_auto_20210712_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintradesbuyorder',
            name='act',
        ),
        migrations.RemoveField(
            model_name='maintradessellorder',
            name='act',
        ),
        migrations.RemoveField(
            model_name='protradesbuyorder',
            name='act',
        ),
        migrations.RemoveField(
            model_name='protradessellorder',
            name='act',
        ),
        migrations.AlterField(
            model_name='maintradessellorder',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellorders', to='exchange.maintrades'),
        ),
        migrations.AlterField(
            model_name='protradesbuyorder',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyorders', to='exchange.protrades'),
        ),
        migrations.AlterField(
            model_name='protradessellorder',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellorders', to='exchange.protrades'),
        ),
    ]
