# Generated by Django 3.2.3 on 2021-07-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0042_auto_20210713_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintradesbuyorder',
            name='start',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='maintradessellorder',
            name='start',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='protradesbuyorder',
            name='start',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='protradessellorder',
            name='start',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
