# Generated by Django 3.2.3 on 2021-07-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0045_auto_20210717_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
