# Generated by Django 3.2.3 on 2021-07-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0046_auto_20210717_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
