# Generated by Django 3.2.3 on 2021-07-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0047_userinfo_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='protrades',
            name='bcurrency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='probuycurrency', to='exchange.currencies'),
        ),
        migrations.AddField(
            model_name='protrades',
            name='scurrency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prosellcurrency', to='exchange.currencies'),
        ),
    ]
