# Generated by Django 3.2.3 on 2021-08-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0048_auto_20210720_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='address2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='key2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccounts',
            name='number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='bankcards',
            name='image',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='bankcards',
            name='number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='verifybankaccountsrequest',
            name='bankc',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='verifybankrequest',
            name='bankc',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='verifymellirequest',
            name='mellic',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
