# Generated by Django 3.2.6 on 2021-09-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0051_alter_userinfo_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rial', models.FloatField(default=1)),
                ('btc', models.FloatField(default=0)),
                ('eth', models.FloatField(default=0)),
                ('trx', models.FloatField(default=0)),
                ('usdt', models.FloatField(default=0)),
                ('doge', models.FloatField(default=0)),
                ('usd', models.FloatField(default=0)),
            ],
        ),
    ]
