# Generated by Django 3.2.6 on 2021-09-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0052_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('leverage', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='bankcards',
            name='image',
        ),
        migrations.RemoveField(
            model_name='verifybankrequest',
            name='bankimg',
        ),
    ]
