# Generated by Django 3.2.6 on 2021-09-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0054_auto_20210909_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencies',
            name='key',
        ),
        migrations.RemoveField(
            model_name='currencies',
            name='pic',
        ),
        migrations.AddField(
            model_name='currencies',
            name='can_deposit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currencies',
            name='can_withdraw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currencies',
            name='chain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currencies',
            name='deposit_least_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currencies',
            name='withdraw_least_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currencies',
            name='withdraw_tx_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='mainwalls',
        ),
    ]
