# Generated by Django 3.2.6 on 2021-09-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0055_auto_20210909_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='key',
            new_name='address2name',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='key2',
            new_name='addressname',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='amount',
        ),
    ]
