# Generated by Django 3.2.6 on 2021-09-12 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0056_auto_20210909_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cp_Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('chain', models.CharField(max_length=100, null=True)),
                ('can_deposit', models.CharField(max_length=100, null=True)),
                ('can_withdraw', models.CharField(max_length=100, null=True)),
                ('deposit_least_amount', models.CharField(max_length=100, null=True)),
                ('withdraw_least_amount', models.CharField(max_length=100, null=True)),
                ('withdraw_tx_fee', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='address2name',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='addressname',
            new_name='key2',
        ),
        migrations.RemoveField(
            model_name='currencies',
            name='can_deposit',
        ),
        migrations.RemoveField(
            model_name='currencies',
            name='can_withdraw',
        ),
        migrations.RemoveField(
            model_name='currencies',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='currencies',
            name='deposit_least_amount',
        ),
        migrations.RemoveField(
            model_name='currencies',
            name='withdraw_least_amount',
        ),
        migrations.RemoveField(
            model_name='currencies',
            name='withdraw_tx_fee',
        ),
        migrations.AddField(
            model_name='currencies',
            name='key',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='currencies',
            name='pic',
            field=models.ImageField(null=True, upload_to='cur'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exchange.currencies'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cp_Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('currency', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exchange.currencies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
