# Generated by Django 3.2.6 on 2021-09-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0057_auto_20210912_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencies',
            name='key',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='key2',
        ),
    ]
