# Generated by Django 3.2.6 on 2021-09-13 07:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0058_auto_20210912_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cp_wallet',
            name='currency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exchange.cp_currencies'),
        ),
        migrations.AlterField(
            model_name='forgetrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 7, 39, 11, 572870, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintradesbuyorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 7, 39, 11, 576158, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintradessellorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 7, 39, 11, 576733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 7, 39, 11, 574474, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='protradesbuyorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 7, 39, 11, 577349, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='protradessellorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 7, 39, 11, 578010, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 7, 39, 11, 571137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 7, 39, 11, 571843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 13, 7, 39, 11, 569969, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Cp_Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 9, 13, 7, 39, 11, 566355, tzinfo=utc))),
                ('chain', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('currency', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exchange.cp_currencies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
