# Generated by Django 3.2.6 on 2021-10-21 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0091_auto_20211021_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyoutrequest',
            name='act',
            field=models.IntegerField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='buyoutrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 761314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='act',
            field=models.IntegerField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 760242, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cp_withdraw',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 766675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='forgetrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 772785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintradesbuyorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 775736, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintradessellorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 776261, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 774318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='perpetualrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 763656, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='protradesbuyorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 776898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='protradessellorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 777415, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 758921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selloutrequest',
            name='act',
            field=models.IntegerField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='selloutrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 762630, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='act',
            field=models.IntegerField(default=2, max_length=15),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 760811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 758137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 771207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 771727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 21, 14, 21, 46, 770092, tzinfo=utc)),
        ),
    ]
