# Generated by Django 3.2.6 on 2021-10-22 21:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0095_auto_20211022_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='googleverify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bankaccounts',
            name='number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='buyoutrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 61517, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 60467, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cp_withdraw',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 66957, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='forgetrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 73678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='levelfee',
            name='buy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='levelfee',
            name='exchange',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='levelfee',
            name='margin',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='levelfee',
            name='perpetual',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='levelfee',
            name='sell',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='maintradesbuyorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 76672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintradessellorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 77328, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 75193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='perpetualrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 63943, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='protradesbuyorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 77854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='protradessellorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 78375, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 59137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selloutrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 62914, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 61013, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 58356, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 72058, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 72594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 22, 21, 23, 11, 70905, tzinfo=utc)),
        ),
    ]
