# Generated by Django 3.1.14 on 2022-06-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.CharField(max_length=100, verbose_name='Withdraw Fee in percents')),
                ('api_name', models.CharField(blank=True, max_length=255, verbose_name='API name')),
                ('secret_key', models.CharField(blank=True, max_length=255, verbose_name='Secret key')),
                ('password_md5', models.CharField(blank=True, max_length=255, verbose_name='Password')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
