# Generated by Django 3.1.14 on 2022-06-26 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255, verbose_name='Currency')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Amount in usd')),
                ('coin_amount', models.IntegerField(blank=True, null=True, verbose_name='Amount in currency')),
                ('address', models.CharField(max_length=60, verbose_name='Deposit address')),
                ('memo', models.CharField(blank=True, max_length=60, verbose_name='Address MEMO')),
                ('recipient_name', models.CharField(max_length=55, verbose_name='Recipient name')),
                ('recipient_email', models.CharField(max_length=55, verbose_name='Recipient_email')),
                ('reference', models.CharField(max_length=55, verbose_name='Extra description')),
                ('manupulated_amount', models.DecimalField(blank=True, decimal_places=4, help_text='Will be computed automatically, but can be changed afterwards.', max_digits=10, null=True, verbose_name='Computed amount after custom FEE applied')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transferred', 'Transferred'), ('canceled', 'Canceled')], max_length=20, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255, verbose_name='Currency')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Amount in usd')),
                ('url', models.CharField(max_length=255, verbose_name='payment_link')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order_id', models.IntegerField(blank=True, verbose_name='order_id')),
                ('manupulated_amount', models.DecimalField(blank=True, decimal_places=4, help_text='Will be computed automatically, but can be changed afterwards.', max_digits=10, null=True, verbose_name='Computed amount after custom FEE applied')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transferred', 'Transferred'), ('canceled', 'Canceled')], max_length=20, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
