# Generated by Django 3.1.14 on 2022-06-28 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20220628_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='tx_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='tx_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Transaction ID'),
        ),
    ]
