# Generated by Django 3.1.14 on 2022-06-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20220628_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositrequest',
            name='order_id',
        ),
    ]
