# Generated by Django 3.1.14 on 2022-06-28 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_auto_20220628_1903'),
        ('request', '0005_remove_depositrequest_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.currencies', verbose_name='Currency'),
        ),
    ]
