# Generated by Django 3.1.14 on 2022-06-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20220628_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount in usd'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='manupulated_amount',
            field=models.FloatField(blank=True, help_text='Will be computed automatically, but can be changed afterwards.', null=True, verbose_name='Computed amount after custom FEE applied'),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount in usd'),
        ),
    ]
