# Generated by Django 3.1.14 on 2022-06-29 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_auto_20220629_1027'),
        ('request', '0007_auto_20220628_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.currencies', verbose_name='Currency'),
        ),
    ]
