# Generated by Django 3.1.14 on 2022-06-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_auto_20220629_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='coin_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount in currency'),
        ),
    ]
