# Generated by Django 3.1.14 on 2022-06-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_auto_20220629_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='manupulated_amount',
            field=models.FloatField(blank=True, help_text='Will be computed automatically, but can be changed afterwards.', null=True, verbose_name='Computed amount after custom FEE applied'),
        ),
    ]
