from django.contrib import admin
from django.urls import path, include
from rest_framework import views
from . import views

urlpatterns = [
   path('review' , views.review.as_view() , name='review'),
   path('levelfee' , views.levelfee.as_view() , name='levelfee'),
   path('buy' , views.buy.as_view() , name='buy'),
   path('buydone' , views.buydone.as_view() , name='buydone'),
   path('buyreject' , views.buyreject.as_view() , name='buyreject'),
   path('withdraw' , views.withdraw.as_view() , name='withdraw'),
   path('buyout' , views.buyout.as_view() , name='buyout'),
   path('sell' , views.sell.as_view() , name='sell'),
   path('sellout' , views.sellout.as_view() , name='sellout'),
   path('selldone' , views.selldone.as_view() , name='selldone'),
   path('buyouthistory' , views.buyouthistory.as_view() , name='buyouthistory'),
   path('sellouthistory' , views.sellouthistory.as_view() , name='sellouthistory'),
   path('buyoutopen' , views.buyoutopen.as_view() , name='buyoutopen'),
   path('selloutopen' , views.selloutopen.as_view() , name='selloutopen'),
   path('changepass' , views.changepass.as_view() , name='changepass'),
   path('levelchange' , views.levelchange.as_view() , name='levelchange'),
   path('wallets/<str:username>' , views.wallets.as_view() , name='wallets'),
   path('staff' , views.staff.as_view() , name='staff'),
   path('subject' , views.subject.as_view() , name='subject'),
   path('subject/<int:id>' , views.subject.as_view() , name='subject'),
   path('ticket' , views.ticket.as_view() , name='ticket'),
   path('ticket/<int:id>' , views.ticket.as_view() , name='ticket'),
   path('bankcards' , views.bankcards.as_view() , name='bankcards'),
   path('bankaccounts' , views.bankaccounts.as_view() , name='bankaccounts'),
   path('verifymelli' , views.verifymelli.as_view() , name='verifymelli'),
   path('verifyaccept' , views.verifyaccept.as_view() , name='verifyaccept'),
   path('cwithdraw' , views.cwithdraw.as_view() , name='cwithdraw'),
   path('rcwithdraw' , views.rcwithdraw.as_view() , name='rcwithdraw'),
   path('ccwithdraw' , views.ccwithdraw.as_view() , name='ccwithdraw'),
   path('perpetualreq' , views.perpetualreq.as_view() , name='perpetualreq'),
   path('perpetualreqccept' , views.perpetualreqccept.as_view() , name='perpetualreqccept'),
   path('perpetualreq/<int:id>' , views.perpetualreq.as_view() , name='perpetualreq'),
   path('general' , views.general.as_view() , name='general'),
   path('USDTP' , views.USDTP.as_view() , name='USDTP'),
   path('user/<str:user>' , views.user.as_view() , name='user'),
   path('verify/<str:user>' , views.verify.as_view() , name='verify'),
   path('userinfo/<str:user>' , views.userinfo.as_view() , name='userinfo'),
   path('users' , views.users.as_view() , name='users'),
   path('mainpageposts' , views.mainpageposts.as_view() , name='mainpageposts'),
   path('topsticker' , views.topsticker.as_view() , name='topsticker'),
   path('transactions' , views.transactions.as_view() , name='transactions'),
   path('profit_rial' , views.profit_rial.as_view() , name='profit_rial'),
   path('bottomsticker' , views.bottomsticker.as_view() , name='bottomsticker'),
   path('otherpages' , views.otherpages.as_view() , name='otherpages'),
   path('editotherpages' , views.editotherpages.as_view() , name='editotherpages'),
   path('details' , views.details.as_view() , name='details'),
   path('mainpageposts/<int:id>' , views.mainpageposts.as_view() , name='mainpageposts'),
   path('topsticker/<int:id>' , views.topsticker.as_view() , name='topsticker'),
   path('bottomsticker/<int:id>' , views.bottomsticker.as_view() , name='bottomsticker'),
   path('otherpages/<int:id>' , views.otherpages.as_view() , name='otherpages'),
   path('cp_wallet/<int:id>' , views.cp_wallet.as_view() , name='cp_wallet'),
   path('cp_history/<int:id>' , views.cp_history.as_view() , name='cp_history'),
   path('cp_history/<str:id>' , views.cp_history.as_view() , name='cp_history'),
]
